- hosts: all
  vars:
   safe_mode_password: "redhat@123"
   path_group: "DC=ad,DC=techtour2019,DC=com"
   ansible_connection: winrm
   ansible_ssh_port: 5986
   ansible_ssh_user: administrator
   ansible_ssh_pass: redhat@123
   ansible_winrm_server_cert_validation: ignore
   ansible_winrm_transport: plaintext
  tasks:
  - name: "Criando o login do desenvolvedor {{ login_desenvolvedor }} no grupo CN=Desenvolvedores,{{ path_group }}"
    win_domain_user:
      name: "{{ login_desenvolvedor }}"
      password: "redhat@123"
      email: "{{ email_desenvolvedor }}"
      state: present
      path: "CN=Users,{{ path_group }}"
      groups:
        - Desenvolvedores
 
