- hosts: 127.0.0.1
  become: no
  vars_prompt:
    - name: "login_openshift"
      prompt: "Comando de login no cluster incluindo token:"
      private: no

  tasks:
  - name: Include variables
    include_vars:
      file: config.yml

  - name: Instala OrangeHRM
    import_role: 
       name: provision-orangehrm
#
