- name: Garante que o usuario desenvolvedor esta no ad
  win_user:
    name: "{{ login_desenvolvedor }}"
    password: redhat@123
    state: present
    groups:
      - Users

- name: Instala Active Directory
  win_feature:
    name: "AD-Domain-Services"
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: result

- name: Instala Dominio
  win_domain:
     dns_domain_name: "{{ dns_name }}"
     safe_mode_password: "{{ safe_mode_password }}"
  register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
  when: ad.changed


- name: Verifica se porta ADWS esta no ar
  win_wait_for:
    port: 9389
    delay: 10
    timeout: 300

- name: Criando Grupo Desenvolvedores
  win_domain_group:
    name: Desenvolvedores
    scope: global
    path: "{{ path_group }}"

- name: Criando o login do desenvolvedor
  win_domain_user:
    name: "{{ login_desenvolvedor }}"
    password: "redhat@123"
    state: present
    path: "CN=Desenvolvedores,{{ path_group }}"
    groups:
      - Desenvolvedores

- debug:
    msg: "Active Directory Instalado!"

